//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class familia
    {
        public familia()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int linea_id { get; set; }
        public System.DateTime creado_el { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public Nullable<System.DateTime> eliminado_el { get; set; }
    
        public virtual linea linea { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
