//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class linea
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> familia_id { get; set; }
    
        public virtual familia familia { get; set; }
    }
}
