//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class costeoEntities : DbContext
    {
        public costeoEntities()
            : base("name=costeoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<costo> costo { get; set; }
        public DbSet<detalle_receta> detalle_receta { get; set; }
        public DbSet<familia> familia { get; set; }
        public DbSet<linea> linea { get; set; }
        public DbSet<precio_venta> precio_venta { get; set; }
        public DbSet<produccion_diaria> produccion_diaria { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<receta> receta { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<unidad_medida> unidad_medida { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
