//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.costo = new HashSet<costo>();
            this.detalle_receta = new HashSet<detalle_receta>();
            this.precio_venta = new HashSet<precio_venta>();
            this.produccion_diaria = new HashSet<produccion_diaria>();
            this.receta = new HashSet<receta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public int fomato { get; set; }
        public int familia_id { get; set; }
        public int unidad_medida_id { get; set; }
        public System.DateTime creado_el { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public Nullable<System.DateTime> eliminado_el { get; set; }
        public Nullable<long> codigo_barra { get; set; }
    
        public virtual ICollection<costo> costo { get; set; }
        public virtual ICollection<detalle_receta> detalle_receta { get; set; }
        public virtual familia familia { get; set; }
        public virtual ICollection<precio_venta> precio_venta { get; set; }
        public virtual ICollection<produccion_diaria> produccion_diaria { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        public virtual ICollection<receta> receta { get; set; }
    }
}
