//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICosteo
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_medida
    {
        public int Id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> creado_el { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public Nullable<System.DateTime> eliminado_el { get; set; }
    }
}
